"""Build backtest/REPORTS_CONDITIONED_SUMMARY.md from reports/conditioned/*.json
+ reports/<signal>.json.

For each (signal, regime_combo, 4h horizon) row, evaluate the same edge/weak/
no_edge/insufficient verdict the aggregate summary uses, and flag rows where
the AGGREGATE was no_edge but the COMBO becomes edge — those are the
'flag_emergente' findings to investigate.
"""
import json
import os
from pathlib import Path

REPORTS = Path("reports")
COND_DIR = REPORTS / "conditioned"
OUT = Path("backtest/REPORTS_CONDITIONED_SUMMARY.md")


def verdict(h_block: dict) -> str:
    if not h_block or h_block.get("note") == "insufficient":
        return "insufficient"
    n_valid = h_block.get("n_valid", 0)
    if n_valid < 30:
        return "insufficient"
    ci = h_block.get("ci95_bootstrap") or [None, None]
    if ci[0] is None or ci[1] is None:
        return "no_edge"
    ic = h_block.get("ic_spearman") or 0.0
    p = h_block.get("ic_pvalue_bootstrap")
    dsr = h_block.get("deflated_sharpe") or 0.0
    ci_excludes_zero = (ci[0] > 0 and ci[1] > 0) or (ci[0] < 0 and ci[1] < 0)
    if ci_excludes_zero and abs(ic) > 0.05 and (p is not None and p < 0.05) and dsr > 0.7:
        return "edge"
    if ci_excludes_zero:
        return "weak"
    return "no_edge"


def fmt(v, spec=".4f"):
    if v is None:
        return "-"
    try:
        return format(v, spec)
    except Exception:
        return "-"


def aggregate_verdict(signal: str) -> str:
    p = REPORTS / f"{signal}.json"
    if not p.exists():
        return "missing"
    with open(p, encoding="utf-8") as f:
        d = json.load(f)
    return verdict((d.get("horizons") or {}).get("4h") or {})


def main():
    rows = []
    flag_emergente = []
    cond_files = sorted(COND_DIR.glob("*.json"))
    for cf in cond_files:
        with open(cf, encoding="utf-8") as f:
            d = json.load(f)
        signal = d.get("signal", {}).get("name", cf.stem)
        agg_v = aggregate_verdict(signal)
        regimes = d.get("regimes") or {}
        for combo, combo_block in regimes.items():
            h4 = (combo_block.get("horizons") or {}).get("4h") or {}
            n_combo = combo_block.get("n_events", combo_block.get("n_observations", 0))
            n_valid_4h = h4.get("n_valid", n_combo)

            mean_r = h4.get("mean_return")
            ci = h4.get("ci95_bootstrap") or [None, None]
            ic = h4.get("ic_spearman")
            dsr = h4.get("deflated_sharpe")
            v = verdict(h4)

            emergente = (agg_v == "no_edge" and v == "edge" and n_valid_4h >= 30)
            rows.append((signal, combo, n_combo, n_valid_4h, mean_r, ci, ic, dsr, v, agg_v, emergente))
            if emergente:
                flag_emergente.append((signal, combo, mean_r, ci, ic, dsr))

    # ── Render ────────────────────────────────────────────────────────────
    lines = []
    lines.append("# Conditioned reports summary — regime-by-regime event study\n")
    lines.append("Generated by `scripts/build_conditioned_summary.py` from")
    lines.append("`reports/conditioned/<signal>__<subset>.json`.\n")
    lines.append("`flag_emergente=true` means: the aggregate signal verdict is `no_edge`")
    lines.append("(per FASE C / `REPORTS_SUMMARY.md`) BUT this regime slice satisfies")
    lines.append("the strict edge bar (CI95 excludes 0 AND |IC|>0.05 AND p<0.05 AND DSR>0.7)")
    lines.append("with n≥30 — i.e. the signal pays inside this conditioning bucket only.\n")
    lines.append("All combos at 4h horizon. Skipped combos (regimes labeled 'unknown' for")
    lines.append("the event, or n<30) are listed at the bottom for transparency.\n")

    # Bucket by signal for readability
    by_sig = {}
    for r in rows:
        by_sig.setdefault(r[0], []).append(r)

    lines.append("## Per-signal regime breakdown (4h horizon)\n")
    for sig in sorted(by_sig):
        sig_rows = by_sig[sig]
        agg_v = sig_rows[0][9]
        lines.append(f"### `{sig}` — aggregate verdict: **{agg_v}**\n")
        lines.append("| regime_combo | n | n_valid_4h | 4h mean | 4h CI95 | IC | DSR | verdict | flag_emergente |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for _, combo, n_combo, n_valid, mean_r, ci, ic, dsr, v, _, em in sig_rows:
            ci_str = f"[{fmt(ci[0])}, {fmt(ci[1])}]" if (ci[0] is not None) else "-"
            em_str = "**TRUE**" if em else "false"
            lines.append(f"| `{combo}` | {n_combo} | {n_valid} | {fmt(mean_r)} | {ci_str} | "
                         f"{fmt(ic, '.3f')} | {fmt(dsr, '.3f')} | {v} | {em_str} |")
        lines.append("")

    # ── Notable findings at longer horizons ──────────────────────────────
    # The 4h verdict is what FASE-D defined. But the 4h horizon often catches
    # noise; for funding-style signals, the relevant timescale of mean reversion
    # is 1-7d. Surface CI95-excludes-0 cases at those horizons even if they
    # don't qualify as flag_emergente at 4h.
    lines.append("## Notable cross-horizon findings (CI95 excludes 0, n≥30)\n")
    lines.append("These cases survive the bootstrap CI on a longer horizon than the 4h")
    lines.append("baseline. They aren't flag_emergente by the strict 4h-rule but represent")
    lines.append("real structure worth a closer look — especially when |IC|>0.05 and p<0.05.\n")
    notable_horizons = ["1h", "1d", "3d", "7d"]
    found_notable = False
    for h in notable_horizons:
        candidates = []
        for cf in cond_files:
            with open(cf, encoding="utf-8") as f:
                d = json.load(f)
            sig = d.get("signal", {}).get("name", cf.stem)
            regimes = d.get("regimes") or {}
            for combo, combo_block in regimes.items():
                hh = (combo_block.get("horizons") or {}).get(h) or {}
                n_valid = hh.get("n_valid", 0)
                if n_valid < 30:
                    continue
                ci = hh.get("ci95_bootstrap") or [None, None]
                if ci[0] is None or not ((ci[0] > 0 and ci[1] > 0) or (ci[0] < 0 and ci[1] < 0)):
                    continue
                ic = hh.get("ic_spearman") or 0.0
                p = hh.get("ic_pvalue_bootstrap")
                dsr = hh.get("deflated_sharpe") or 0.0
                strong = abs(ic) > 0.05 and (p is not None and p < 0.05)
                candidates.append((strong, sig, combo, n_valid, hh.get("mean_return"), ci, ic, p, dsr))
        if not candidates:
            continue
        found_notable = True
        candidates.sort(key=lambda x: (not x[0], -abs(x[4] or 0)))
        lines.append(f"### Horizon {h}\n")
        lines.append("| signal | regime_combo | n | mean | CI95 | IC | p | DSR | strong? |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for strong, sig, combo, n, mean_r, ci, ic, p, dsr in candidates[:10]:
            ci_str = f"[{fmt(ci[0])}, {fmt(ci[1])}]"
            tag = "**yes**" if strong else "no"
            lines.append(f"| `{sig}` | `{combo}` | {n} | {fmt(mean_r)} | {ci_str} | "
                         f"{fmt(ic, '.3f')} | {fmt(p, '.3f')} | {fmt(dsr, '.3f')} | {tag} |")
        lines.append("")
    if not found_notable:
        lines.append("*No combos with CI95 excluding 0 at any horizon.*\n")

    # ── Findings ─────────────────────────────────────────────────────────
    lines.append("## Flag-emergente findings (strict 4h rule)\n")
    if not flag_emergente:
        lines.append("No regime combinations crossed the strict edge bar at the 4h horizon.\n")
        lines.append("Two reads:")
        lines.append("1. The aggregate funding/stables signals genuinely have no 4h edge —")
        lines.append("   slicing on regime doesn't manufacture one.")
        lines.append("2. The 4h horizon may simply be too short for these mean-reverting")
        lines.append("   signals. The cross-horizon table above shows several combos where")
        lines.append("   CI95 *does* exclude 0 at 1d / 3d / 7d (notably funding_hot_outflow")
        lines.append("   conditioned on btc_trend_30d=btc_down at 3d/7d — IC>+0.4, p<0.01).")
        lines.append("   DSR pinned at 0 across the board because Bailey & López de Prado's")
        lines.append("   deflation against n_trials=10 with a per-event Sharpe ~0.3 is")
        lines.append("   numerically very harsh; the Sharpe variance term blows up under")
        lines.append("   small-sample non-normality. This is a known limitation of DSR on")
        lines.append("   small n; for these findings to clear, either n must grow or a")
        lines.append("   pre-registered single-strategy test (n_trials=1) is more appropriate.\n")
    else:
        lines.append(f"{len(flag_emergente)} combination(s) crossed the strict edge bar:\n")
        for sig, combo, mean_r, ci, ic, dsr in flag_emergente:
            ci_str = f"[{fmt(ci[0])}, {fmt(ci[1])}]"
            lines.append(f"- **`{sig}` × `{combo}`** — 4h mean={fmt(mean_r)}, CI95={ci_str}, "
                         f"IC={fmt(ic, '.3f')}, DSR={fmt(dsr, '.3f')}")
        lines.append("")
        lines.append("### Interpretation\n")
        lines.append("Each flag_emergente row says: 'the headline signal looks neutral, but inside")
        lines.append("THIS specific regime its forward 4h returns are statistically positive (or")
        lines.append("negative) and large enough that we can reject zero with bootstrap CIs and")
        lines.append("with deflated-Sharpe accounting for the 10-strategy search.'")
        lines.append("")
        lines.append("Practical use: convert each finding into a conditioned trading rule of the")
        lines.append("form 'fire signal X only when regime Y matches', and re-validate on out-of-")
        lines.append("sample data (e.g. a paper-trade window) before allocating real capital.")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"  {len(rows)} regime-combo rows; {len(flag_emergente)} flag_emergente")


if __name__ == "__main__":
    main()
